kotlin.code.style=official
StudioRunPath=/Users/dong/Applications/Android Studio.app/Contents
ideVersion=2024.3.1.2

ali_public=https\://maven.aliyun.com/repository/public
ali_google=https\://maven.aliyun.com/repository/google
ali_gradle=https\://maven.aliyun.com/repository/gradle-plugin

kotlin.stdlib.default.dependency=false
org.gradle.caching=true
org.gradle.parallel=true

org.gradle.jvmargs=-Xmx4g
kotlin.daemon.jvmargs=-Xmx4g
